bugfix: waiting for idle backends had a type mismatch and thus failed with
  File "/nix/store/dprg2jcgbz55bddszk22siky106351cv-skvaider-env/lib/python3.12/site-packages/skvaider/routers/openai.py", line 340, in assign_backends
     model = backend.models[model_id]
             ^^^^^^^^^^^^^^
 AttributeError: '_asyncio.Task' object has no attribute 'models'